# Generated by Django 6.0.2 on 2026-03-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("SHINHAN", "신한Big카드"),
                    ("WOORI", "우리은행통장"),
                    ("CASH", "현금"),
                    ("ETC", "기타"),
                ],
                max_length=20,
                verbose_name="결제방식",
            ),
        ),
    ]
