# Generated by Django 6.0.2 on 2026-03-06 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="연도")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="월",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BEAUTY", "미용"),
                            ("HOUSEHOLD", "생활용품"),
                            ("PHONE_BILL", "통신비"),
                            ("ALLOWANCE", "자유금"),
                            ("FOOD", "식대"),
                            ("MEDICAL", "병원비"),
                            ("TRANSPORT", "교통비"),
                            ("HOUSING", "주거"),
                            ("CLOTHING", "의복"),
                            ("EVENT", "이벤트"),
                            ("EXERCISE", "운동"),
                            ("UNKNOWN", "미상"),
                            ("SUBSCRIPTION", "청약"),
                            ("SELF_DEV", "자기개발"),
                            ("CELEBRATION", "경조사"),
                            ("ETC", "기타"),
                            ("UNSETTLED", "미정산"),
                        ],
                        default="UNSETTLED",
                        max_length=20,
                        verbose_name="대분류",
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        choices=[
                            ("BEAUTY", "미용"),
                            ("HOUSEHOLD", "생활용품"),
                            ("PHONE_BILL", "통신비"),
                            ("ALLOWANCE_MS", "민성자유금"),
                            ("ALLOWANCE_MK", "민근자유금"),
                            ("ALCOHOL", "주류"),
                            ("BEVERAGE", "음료"),
                            ("DELIVERY", "배달/포장"),
                            ("DINING_OUT", "외식"),
                            ("COOKING", "요리"),
                            ("COMPANY_MEAL", "회사식대"),
                            ("HOSPITAL_ETC", "기타병원비"),
                            ("REGULAR_CHECKUP", "정기진료"),
                            ("TRANSPORT", "교통비"),
                            ("ELECTRICITY", "전기요금"),
                            ("WATER", "수도요금"),
                            ("GAS", "가스요금"),
                            ("MAINTENANCE", "관리비"),
                            ("LEASE_INTEREST", "전세이자"),
                            ("INTERNET", "인터넷요금"),
                            ("CLOTHING_BUY", "의복구입"),
                            ("CLOTHING_CARE", "의복관리"),
                            ("VACATION", "휴가"),
                            ("LEISURE", "놀이"),
                            ("PARENTS", "친정"),
                            ("EXERCISE_GOODS", "운동용품"),
                            ("EXERCISE_FEE", "운동이용료"),
                            ("UNKNOWN", "미상"),
                            ("SUBSCRIPTION", "청약"),
                            ("LEARNING", "학습"),
                            ("CELEBRATION", "경조사"),
                            ("INSURANCE", "보험료"),
                            ("ETC", "기타"),
                            ("UNSETTLED", "미정산"),
                        ],
                        default="UNSETTLED",
                        max_length=20,
                        verbose_name="소분류",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="예산")),
                ("memo", models.TextField(blank=True, default="", verbose_name="비고")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "budget",
                "ordering": ["-year", "-month", "category"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "month", "category", "sub_category"),
                        name="unique_budget_per_month",
                    )
                ],
            },
        ),
    ]
